### ISSUE TITLE
event-12 の presenter にコンタクトし必要事項の確認

### ISSUE THREAD

**Issue by usagi** [otona-after5/main#4]
- [x] 開催日として選択可能な日付を入手
- [x] 開催日を通知（ rel. #3 ）
- [x] 会場に関する希望を確認
- [x] タイトルと時間の希望を確認

**Comment by dorapanda** [comment]
発表タイトルと発表概要はヒアリング済み。
CONNPASSの下書きに記入。

**Comment by dorapanda** [comment]
現時点での開催候補日。
- 4/8（金）
- 4/15（金）
- 4/22（金）

**Comment by usagi** [comment]
:+1:

**Comment by usagi** [comment]
じゃ、とりあえず8日で計画しようか。

**Comment by usagi** [comment]
@dorapanda 「とりあえず8日で企画調整はいります」的な案内よろしくー。ついでにこれチェックしてもらえると。

![image](https://cloud.githubusercontent.com/assets/115972/13033746/6d62e732-d365-11e5-9cf5-ce602630bfd0.png)

**Comment by dorapanda** [comment]
グレーアウトされててチェックできないのですが、なにかやり方があるのかな。

**Comment by usagi** [comment]
ほうほう、メンバーの権限グループかな。グループ作っただけで権限設定してなかったので運営メンバーとは名ばかりになってるのかも。ちょいいじってきます。

**Comment by usagi** [comment]
@dorapanda たぶんなんでもできる super user になったはず。
