### ISSUE TITLE
event-12: 会場手配

### ISSUE THREAD

**Issue by usagi** [otona-after5/main#5]
- [x] 会場候補決定 ( rel. #4 )
- [x] 会場調整開始 ( 会場の企画担当者と日時や金額や書類について必要な事前の連絡や調整を行う )
- [x] 会場確保 ( 会場の使用権が得られたならば報告してチケットを閉じる )

**Comment by dorapanda** [comment]
今のところの候補。

#### 場所
- MIRAI.ST
- 市民ホール

#### 日にち
- 4/8（金）
- 4/15（金）
- 4/22（金）

**Comment by usagi** [comment]
8日、ミライストで調整開始。担当わたしでOK

**Comment by usagi** [comment]
明日 2016-02-15 23:59 までに書類作ってミライストに投げとく予定。

**Comment by usagi** [comment]
すっかり忘れてたので今かいてる。

**Comment by usagi** [comment]
@otona-after5/executors ミライストカフェ申請書

https://www.dropbox.com/home/otona-after5/mirai.st%20cafe?preview=MIRAIST_event_application-otona%2312.xlsx

**Comment by usagi** [comment]
ミライストカフェの服部さんに↑添付でメールしといた。

**Comment by usagi** [comment]
↑確保完了。
